# Generated by Django 2.2 on 2020-06-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='new', max_length=20),
            preserve_default=False,
        ),
    ]
