# Generated by Django 2.2.13 on 2020-06-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_auto_20200617_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
