# Generated by Django 2.2.13 on 2020-06-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0005_auto_20200617_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
