# Generated by Django 2.1.5 on 2020-06-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0006_auto_20200617_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
