# Generated by Django 2.2.13 on 2020-06-17 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0009_auto_20200618_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='time',
        ),
    ]
