# Generated by Django 2.2.13 on 2020-06-17 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0010_remove_reply_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
