# Generated by Django 2.2.13 on 2020-06-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0011_reply_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='forum_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
