# Generated by Django 2.2.13 on 2020-06-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0012_auto_20200618_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='forum_code',
            field=models.CharField(max_length=10),
        ),
    ]
