# Generated by Django 2.2.13 on 2020-06-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0013_auto_20200618_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
