# Generated by Django 2.2.13 on 2020-06-19 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0016_auto_20200618_0057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forum',
        ),
    ]
