# Generated by Django 2.2.13 on 2020-06-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0018_question_forum'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('slug', models.SlugField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
