# Generated by Django 2.2.13 on 2020-06-19 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0019_publicquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('time', models.DateTimeField()),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qna.PublicQuestion')),
            ],
        ),
    ]
