# Generated by Django 2.2.13 on 2020-06-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0020_publicreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicreply',
            name='if_porf',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
