# Generated by Django 2.2.13 on 2020-06-20 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0021_publicreply_if_porf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicreply',
            old_name='if_porf',
            new_name='if_prof',
        ),
    ]
