# Generated by Django 2.2.13 on 2020-06-24 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0024_auto_20200624_1302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
        migrations.RenameModel(
            old_name='BlogLinks',
            new_name='BlogLink',
        ),
    ]
