# Generated by Django 2.2.13 on 2020-06-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0025_auto_20200624_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='null'),
            preserve_default=False,
        ),
    ]
