# Generated by Django 2.2.13 on 2020-06-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0028_auto_20200624_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicquestion',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
