# Generated by Django 2.2.13 on 2020-10-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0030_auto_20200713_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicquestion',
            name='ip',
        ),
        migrations.AddField(
            model_name='publicquestion',
            name='n_of_replies',
            field=models.IntegerField(default=0),
        ),
    ]
