# Generated by Django 2.2.13 on 2021-06-24 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0031_auto_20201013_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepliesReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('time', models.DateTimeField()),
                ('if_prof', models.CharField(blank=True, max_length=50, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qna.PublicReply')),
            ],
        ),
    ]
